version: "3.8"

services:
  mysql:
    image: mysql:8.0.35
    container_name: zabbix-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  zabbix-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zabbix-server
    environment:
      DB_HOST: mysql
      DB_NAME: zabbix
      DB_USER: zabbix
      DB_PASSWORD: zabbix
    ports:
      - "10051:10051"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
